/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.DanhSachHangHoa;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.HangHoa;

/**
 *
 * @author Thanh
 */
public class UngDungQuanLyHangHoa extends javax.swing.JFrame {

    DanhSachHangHoa list = new DanhSachHangHoa();
    String currentDate = LocalDate.now().toString();
    String fileName = "danhsach_hanghoa.txt";

    /**
     * Creates new form UngDungQuanLyHangHoa
     */
    public UngDungQuanLyHangHoa() {
        hienthi();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        view = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JPanel();
        tieude = new javax.swing.JLabel();
        fields = new javax.swing.JPanel();
        thuoctinhchinh = new javax.swing.JLabel();
        mahanghoa = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMaHH = new javax.swing.JTextField();
        tenhanghoa = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtTenHH = new javax.swing.JTextField();
        soluong = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        giaban = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtGiaBan = new javax.swing.JTextField();
        ngaysanxuat = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtNgaySanXuat = new javax.swing.JTextField();
        noisanxuat = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtNoiSX = new javax.swing.JTextField();
        crud = new javax.swing.JPanel();
        mota = new javax.swing.JLabel();
        btnXoa = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        controller = new javax.swing.JPanel();
        hienthif = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDSHangHoa = new javax.swing.JTable();
        hienthi = new javax.swing.JPanel();
        xuatdanhsach = new javax.swing.JPanel();
        mota2 = new javax.swing.JLabel();
        btnXuatDS = new javax.swing.JButton();
        sapxep = new javax.swing.JPanel();
        mota3 = new javax.swing.JLabel();
        btnSapXep = new javax.swing.JButton();
        docghifile = new javax.swing.JPanel();
        mota1 = new javax.swing.JLabel();
        btnDoc = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        view.setLayout(new javax.swing.BoxLayout(view, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        title.setLayout(new javax.swing.BoxLayout(title, javax.swing.BoxLayout.LINE_AXIS));

        tieude.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        tieude.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tieude.setText("Ứng dụng quản lý nhập hàng");
        title.add(tieude);

        jPanel1.add(title);

        fields.setLayout(new java.awt.GridLayout(0, 1, 4, 4));

        thuoctinhchinh.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        thuoctinhchinh.setText("Thuộc tính chính:");
        thuoctinhchinh.setMaximumSize(new java.awt.Dimension(200, 22));
        thuoctinhchinh.setMinimumSize(new java.awt.Dimension(200, 22));
        fields.add(thuoctinhchinh);

        mahanghoa.setLayout(new java.awt.GridLayout(1, 0, 4, 4));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mã hàng hóa");
        mahanghoa.add(jLabel1);

        txtMaHH.setMinimumSize(new java.awt.Dimension(6, 30));
        mahanghoa.add(txtMaHH);

        fields.add(mahanghoa);

        tenhanghoa.setLayout(new java.awt.GridLayout(1, 0, 4, 4));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tên hàng hóa");
        tenhanghoa.add(jLabel2);

        txtTenHH.setMinimumSize(new java.awt.Dimension(6, 30));
        tenhanghoa.add(txtTenHH);

        fields.add(tenhanghoa);

        soluong.setLayout(new java.awt.GridLayout(1, 0, 4, 4));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Số lượng");
        soluong.add(jLabel6);

        txtSoLuong.setMinimumSize(new java.awt.Dimension(6, 30));
        txtSoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoLuongActionPerformed(evt);
            }
        });
        soluong.add(txtSoLuong);

        fields.add(soluong);

        giaban.setLayout(new java.awt.GridLayout(1, 0, 4, 4));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Giá bán");
        giaban.add(jLabel3);

        txtGiaBan.setMinimumSize(new java.awt.Dimension(6, 30));
        giaban.add(txtGiaBan);

        fields.add(giaban);

        ngaysanxuat.setLayout(new java.awt.GridLayout(1, 0, 4, 4));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Ngày sản xuất");
        ngaysanxuat.add(jLabel4);

        txtNgaySanXuat.setMinimumSize(new java.awt.Dimension(6, 30));
        ngaysanxuat.add(txtNgaySanXuat);

        fields.add(ngaysanxuat);

        noisanxuat.setLayout(new java.awt.GridLayout(1, 0, 4, 4));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Nơi sản xuất");
        noisanxuat.add(jLabel5);

        txtNoiSX.setMinimumSize(new java.awt.Dimension(6, 30));
        txtNoiSX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoiSXActionPerformed(evt);
            }
        });
        noisanxuat.add(txtNoiSX);

        fields.add(noisanxuat);

        jPanel1.add(fields);

        view.add(jPanel1);

        crud.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        crud.setLayout(new java.awt.GridLayout(1, 0));

        mota.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mota.setText("Chức năng chính");
        mota.setMaximumSize(new java.awt.Dimension(200, 22));
        mota.setMinimumSize(new java.awt.Dimension(200, 22));
        crud.add(mota);

        btnXoa.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        crud.add(btnXoa);

        btnThem.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        crud.add(btnThem);

        btnSua.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        crud.add(btnSua);

        view.add(crud);

        controller.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        controller.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        controller.setLayout(new javax.swing.BoxLayout(controller, javax.swing.BoxLayout.PAGE_AXIS));
        view.add(controller);

        hienthif.setLayout(new javax.swing.BoxLayout(hienthif, javax.swing.BoxLayout.LINE_AXIS));

        tblDSHangHoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sản phẩm", "Tên Sản phẩm", "Giá bán", "Số Lượng", "Ngày Sản Xuất", "Nơi Sản xuất"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblDSHangHoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSHangHoaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDSHangHoa);

        hienthif.add(jScrollPane1);

        hienthi.setLayout(new java.awt.GridLayout(3, 1, 4, 4));

        xuatdanhsach.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        xuatdanhsach.setLayout(new java.awt.GridLayout(2, 0, 4, 4));

        mota2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        mota2.setText("Hiển thị");
        xuatdanhsach.add(mota2);

        btnXuatDS.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnXuatDS.setText("Xuất danh sách");
        btnXuatDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatDSActionPerformed(evt);
            }
        });
        xuatdanhsach.add(btnXuatDS);

        hienthi.add(xuatdanhsach);

        sapxep.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sapxep.setLayout(new java.awt.GridLayout(2, 0, 4, 4));

        mota3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        mota3.setText("Sắp xếp");
        sapxep.add(mota3);

        btnSapXep.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnSapXep.setText("Sắp xếp danh sách");
        btnSapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSapXepActionPerformed(evt);
            }
        });
        sapxep.add(btnSapXep);

        hienthi.add(sapxep);

        docghifile.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        docghifile.setLayout(new java.awt.GridLayout(3, 0));

        mota1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        mota1.setText("Đọc ghi file");
        docghifile.add(mota1);

        btnDoc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnDoc.setText("Đọc file");
        btnDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocActionPerformed(evt);
            }
        });
        docghifile.add(btnDoc);

        btnLuu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnLuu.setText("Ghi file");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });
        docghifile.add(btnLuu);

        hienthi.add(docghifile);

        hienthif.add(hienthi);

        view.add(hienthif);

        getContentPane().add(view);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXuatDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatDSActionPerformed

        hienthi();
    }//GEN-LAST:event_btnXuatDSActionPerformed
    private void hienthi() {
        if (list.getData().isEmpty()) {
            return;
        }
        DefaultTableModel tableModel = (DefaultTableModel) tblDSHangHoa.getModel();
        tableModel.setRowCount(0);
        // TableDanhSachHangHoa = new JTable(data, columns);
        for (HangHoa value : list.getData()) {
            Object[] data;
            data = new Object[]{value.getMa(), value.getTen(), value.getDonGia(), value.getSoluong(), value.getNgaySX(), value.getNoisx()};
            tableModel.addRow(data);
        }

        tableModel.fireTableDataChanged();
    }
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed

        if ("".equals(txtMaHH.getText())
                || "".equals(txtTenHH.getText())
                || "".equals(txtNgaySanXuat.getText())
                || "".equals(txtNoiSX.getText())
                || "".equals(txtGiaBan.getText())
                || "".equals(txtSoLuong.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Chua nhap day du du lieu truoc khi them moi");
        }
        try {
            HangHoa hh = new HangHoa();
            hh.setMa(txtMaHH.getText());
            hh.setTen(txtTenHH.getText());
            hh.setDonGia(Integer.parseInt(txtGiaBan.getText()));
            hh.setSoluong(Integer.parseInt(txtSoLuong.getText()));
            hh.setNgaySX(txtNgaySanXuat.getText());
            hh.setNoisx(txtNoiSX.getText());
            boolean check = list.Them(hh);
            if (check) {
                System.out.println("Them thanh cong");
                hienthi();
            } else {
                System.out.println("Them khong thanh cong");
                JOptionPane.showMessageDialog(rootPane, "Hang hoa da co trong danh sach");
            }
        } catch (NumberFormatException e) {
            String s = e.getMessage();
            System.out.println(e.getMessage());

        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSapXepActionPerformed
        list.SapXep();
        hienthi();
    }//GEN-LAST:event_btnSapXepActionPerformed

    private void txtNoiSXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoiSXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoiSXActionPerformed

    private void txtSoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLuongActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        if ("".equals(txtMaHH.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Chua chon ma hang hoa");
        }
        DefaultTableModel detbl = (DefaultTableModel) tblDSHangHoa.getModel();

        HangHoa hh = new HangHoa(txtMaHH.getText());
        boolean check = list.Xoa(hh);
        if (check) {
            JOptionPane.showMessageDialog(rootPane, "Xoa Thanh cong");
            detbl.removeRow(tblDSHangHoa.getSelectedRow());
            hienthi();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Xoa Khong Thanh cong");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        if ("".equals(txtMaHH.getText())
                || "".equals(txtTenHH.getText())
                || "".equals(txtNgaySanXuat.getText())
                || "".equals(txtNoiSX.getText())
                || "".equals(txtGiaBan.getText())
                || "".equals(txtSoLuong.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Chua nhap day du du lieu truoc khi them moi");
        }
        try {
            HangHoa hh = new HangHoa();
            hh.setMa(txtMaHH.getText());
            hh.setTen(txtTenHH.getText());
            hh.setDonGia(Integer.parseInt(txtGiaBan.getText()));
            hh.setSoluong(Integer.parseInt(txtSoLuong.getText()));
            hh.setNgaySX(txtNgaySanXuat.getText());
            hh.setNoisx(txtNoiSX.getText());
            System.out.println(hh.toString());
            boolean check = list.Sua(hh);
            if (check) {
                System.out.println("Sua thanh cong");
                JOptionPane.showMessageDialog(rootPane, "Sua Thanh cong");
                hienthi();
            } else {
                System.out.println("Sua khong thanh cong");
                JOptionPane.showMessageDialog(rootPane, "Sua khong Thanh cong");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocActionPerformed

        try {
            list.DocFile(fileName);
            hienthi();
        } catch (Exception e) {
            System.out.println("Khong the doc file");
            JOptionPane.showMessageDialog(rootPane, "Khong the doc file");
        }
    }//GEN-LAST:event_btnDocActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        try {
            list.GhiFile(fileName);
        } catch (Exception e) {
            System.out.println("Khong the ghi file");
            JOptionPane.showMessageDialog(rootPane, "Khong the ghi file");
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void tblDSHangHoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSHangHoaMouseClicked
        int colMaSP = 0;// column mã sản phẩm
        int colTenSP = 1;// column tên sản phẩm        
        int colGiaSP = 2;// column loai sản phẩm
        int colSoLuong = 3;// column giá sản phẩm
        int colNgaySX = 4;
        int colNoiSX = 5;
        DefaultTableModel tableModel = (DefaultTableModel) tblDSHangHoa.getModel();
        // chọn row trên table
        int row = tblDSHangHoa.getSelectedRow();

        // lấy giá trị từng cột
        String maSP = tableModel.getValueAt(row, colMaSP).toString();
        String tenSP = tableModel.getValueAt(row, colTenSP).toString();
        int giaSP = Integer.parseInt(tableModel.getValueAt(row, colGiaSP).toString());
        int soLuong = Integer.parseInt(tableModel.getValueAt(row, colSoLuong).toString());
        String ngaySX = tableModel.getValueAt(row, colNgaySX).toString();
        String noiSX = tableModel.getValueAt(row, colNoiSX).toString();
        // chọn xong nhập thông tin trên form
        txtMaHH.setText(maSP);
        txtTenHH.setText(tenSP);
        txtGiaBan.setText(giaSP + "");
        txtSoLuong.setText(soLuong + "");
        txtNgaySanXuat.setText(ngaySX);
        txtNoiSX.setText(noiSX);
    }//GEN-LAST:event_tblDSHangHoaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UngDungQuanLyHangHoa.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UngDungQuanLyHangHoa.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UngDungQuanLyHangHoa.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UngDungQuanLyHangHoa.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new UngDungQuanLyHangHoa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoc;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnSapXep;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXuatDS;
    private javax.swing.JPanel controller;
    private javax.swing.JPanel crud;
    private javax.swing.JPanel docghifile;
    private javax.swing.JPanel fields;
    private javax.swing.JPanel giaban;
    private javax.swing.JPanel hienthi;
    private javax.swing.JPanel hienthif;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mahanghoa;
    private javax.swing.JLabel mota;
    private javax.swing.JLabel mota1;
    private javax.swing.JLabel mota2;
    private javax.swing.JLabel mota3;
    private javax.swing.JPanel ngaysanxuat;
    private javax.swing.JPanel noisanxuat;
    private javax.swing.JPanel sapxep;
    private javax.swing.JPanel soluong;
    private javax.swing.JTable tblDSHangHoa;
    private javax.swing.JPanel tenhanghoa;
    private javax.swing.JLabel thuoctinhchinh;
    private javax.swing.JLabel tieude;
    private javax.swing.JPanel title;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtMaHH;
    private javax.swing.JTextField txtNgaySanXuat;
    private javax.swing.JTextField txtNoiSX;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenHH;
    private javax.swing.JPanel view;
    private javax.swing.JPanel xuatdanhsach;
    // End of variables declaration//GEN-END:variables
}
